// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "AIFlowActorBlackboardHelper.h"
#include "Nodes/AIFlowNode.h"

#include "FlowNode_GetBlackboardValues.generated.h"

// Forward Declarations
class UFlowBlackboardEntryValue;

/**
 * Get blackboard values and provide them as output data pins
 */
UCLASS(DisplayName = "Get Blackboard Values")
class AIFLOW_API UFlowNode_GetBlackboardValues : public UAIFlowNode
{
	GENERATED_BODY()

public:

	UFlowNode_GetBlackboardValues();

	// UFlowNodeBase
	virtual void UpdateNodeConfigText_Implementation() override;
	// --

	// IFlowDataPinValueSupplierInterface
	virtual FFlowDataPinResult TrySupplyDataPin_Implementation(FName PinName) const override;
	// --
	
#if WITH_EDITOR
public:

	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return Super::SupportsContextPins() || !BlackboardEntries.IsEmpty(); }
	// --

	// UObject
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChangedEvent) override;
	// --

	// IFlowDataPinGeneratorInterface
	virtual void AutoGenerateDataPins(FFlowAutoDataPinsWorkingData& InOutWorkingData) const override;
	// --

	// IFlowBlackboardAssetProvider
	virtual UBlackboardData* GetBlackboardAssetForPropertyHandle(const TSharedPtr<IPropertyHandle>& PropertyHandle) const override;
	// --

protected:

	void AppendEntriesForEveryActor(FTextBuilder& InOutTextBuilder) const;

	UBlackboardData* GetBlackboardAssetForEditor() const;
#endif // WITH_EDITOR

protected:

	static UBlackboardKeyType* GetBlackboardKeyTypeFromBlackboardKeyName(const UBlackboardData* BlackboardAsset, const FName& KeyName);

	UBlackboardComponent* GetBlackboardComponentToApplyTo() const;
	AActor* TryResolveActorForBlackboard() const;

protected:

	// Optional specific actor to use for the blackboard query.
	// If not specified, will use the flow graph's owning actor.
	UPROPERTY(Transient, meta = (DefaultForInputFlowPin, FlowPinType = "Object", DisplayPriority = 2))
	TObjectPtr<AActor> SpecificActor = nullptr;

	// Specific blackboard to use (optional, defaults to the flow asset's blackboard)
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Specific Blackboard", meta = (DisplayPriority = 2))
	TObjectPtr<UBlackboardData> SpecificBlackboardAsset = nullptr;

	// Blackboard entries to get from the blackboard and output as data pins
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Blackboard Entries", meta = (DisplayPriority = 3))
	TArray<FFlowBlackboardEntry> BlackboardEntries;
	
	// Search rule to use to find the "Specific Blackboard" (if specified)
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Specific Blackboard Search Rule", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	EActorBlackboardSearchRule SpecificBlackboardSearchRule = EActorBlackboardSearchRule::ActorAndControllerAndGameState;

	static FName INPIN_SpecificActor;
};
