// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "AIFlowActorBlackboardHelper.h"
#include "Nodes/AIFlowNode.h"
#include "Types/FlowBlackboardEntry.h"
#include "Types/FlowInjectComponentsManager.h"
#include "BehaviorTree/BlackboardComponent.h"
#include "BehaviorTree/Blackboard/BlackboardKeyWrappers.h"

#include "FlowNode_SetBlackboardValuesV2.generated.h"

// Forward Declarations
class UFlowBlackboardEntryValue;

/**
* Set blackboard values to the values defined in the Entries array
* on one or more actors' blackboards.
*
* Actors can be:
*   • Specific actors supplied via the SpecificActors pin
*   • The flow graph's owning actor (fallback)
*/
UCLASS(DisplayName = "Set Blackboard Values V2")
class AIFLOW_API UFlowNode_SetBlackboardValuesV2 : public UAIFlowNode
{
	GENERATED_BODY()

public:
	UFlowNode_SetBlackboardValuesV2();

	// IFlowCoreExecutableInterface
	virtual void ExecuteInput(const FName& PinName) override;
	virtual void DeinitializeInstance() override;
	// --

	// UFlowNodeBase
	virtual void UpdateNodeConfigText_Implementation() override;
	// --

#if WITH_EDITOR
	// UObject
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChangedEvent) override;
	// --

	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return !EntriesForEveryActor.Entries.IsEmpty(); }
	// --

	// IFlowDataPinGeneratorInterface
	virtual void AutoGenerateDataPins(FFlowAutoDataPinsWorkingData& InOutWorkingData) const override;
	// --

	// IFlowBlackboardAssetProvider
	virtual UBlackboardData* GetBlackboardAssetForPropertyHandle(const TSharedPtr<IPropertyHandle>& PropertyHandle) const override;
	// --
#endif

protected:
	// Actor resolution
	virtual TArray<AActor*> TryResolveActorsForBlackboard() const;
	bool TryAddSpecificActors(TArray<AActor*>& InOutResolvedActors) const;
	// --

	// Blackboard handling helpers (from base class)
	TArray<UBlackboardComponent*> GetBlackboardComponentsToApplyTo() const;
	void EnsureInjectComponentsManager();
	void CleanupInjectComponentsManager();
	// --

	UFUNCTION()
	void OnBeforeActorRemoved(AActor* RemovedActor);

	// Functions for subclasses to apply additional monitoring to Actors
	virtual void OnStartMonitoringActor(AActor& Actor) { }
	virtual void OnStopMonitoringActor(AActor& Actor) { }

	virtual bool TryFindPropertyByPinName(
		const UObject& PropertyOwnerObject,
		const FName& PinName,
		const FProperty*& OutFoundProperty,
		TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct) const override;
	// --

	// Editor helpers
#if WITH_EDITOR
	void AppendEntriesForEveryActor(FTextBuilder& InOutTextBuilder) const;
	UBlackboardData* GetBlackboardAssetForEditor() const;
#endif // WITH_EDITOR
	// --

protected:
	// Blackboard properties to set on each actor this node is applied to
	UPROPERTY(EditAnywhere, Category = BlackboardEntriesToSet, meta = (ShowOnlyInnerProperties, DisplayPriority = 0))
	FAIFlowConfigureBlackboardOption EntriesForEveryActor;

	// Configured blackboard entry option sets to apply to actors
	UPROPERTY(EditAnywhere, Category = BlackboardEntriesToSet, DisplayName = "Per-Actor Blackboard Entries", meta = (DisplayPriority = 1))
	TArray<FAIFlowConfigureBlackboardOption> PerActorOptions;

	// Method to use when applying the Per-Actor Options
	UPROPERTY(EditAnywhere, Category = BlackboardEntriesToSet, DisplayName = "Per-Actor Assignment Method", meta = (DisplayPriority = 1))
	EPerActorOptionsAssignmentMethod PerActorOptionsAssignmentMethod = EPerActorOptionsAssignmentMethod::InOrderWithWrapping;

	// Optional specific actors to use to look for (or inject) the blackboard.
	UPROPERTY(Transient, meta = (DefaultForInputFlowPin, FlowPinType = "Object", DisplayPriority = 1))
	TArray<AActor*> SpecificActors;

	// Specific blackboard to use (optional, defaults to the flow asset's blackboard)
	UPROPERTY(EditAnywhere, Category = BlackboardAsset, DisplayName = "Specific Blackboard", meta = (DisplayPriority = 2))
	TObjectPtr<UBlackboardData> SpecificBlackboardAsset = nullptr;

	// Search rule to use to find the "Specific Blackboard" (if specified)
	UPROPERTY(EditAnywhere, Category = BlackboardAsset, DisplayName = "Blackboard Search Rule", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	EActorBlackboardSearchRule SpecificBlackboardSearchRule = EActorBlackboardSearchRule::ActorAndControllerAndGameState;

	// Injection rule for a missing blackboard on the actor
	UPROPERTY(EditAnywhere, Category = BlackboardAsset, DisplayName = "Blackboard Injection Rule", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	EActorBlackboardInjectRule InjectRule = EActorBlackboardInjectRule::DoNotInjectIfMissing;

	// Specific blackboard component subclass to use (optional, defaults to the flow asset's blackboard defined component class)
	UPROPERTY(EditAnywhere, AdvancedDisplay, Category = BlackboardAsset, DisplayName = "Specific Blackboard Component", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	TSubclassOf<UBlackboardComponent> SpecificBlackboardComponentClass = nullptr;

	// Helper struct that shared functionality for manipulating Actor blackboards
	UPROPERTY()
	FAIFlowActorBlackboardHelper ActorBlackboardHelper;

	// Manager object to inject and remove components from actors
	UPROPERTY(Transient)
	TObjectPtr<UFlowInjectComponentsManager> InjectComponentsManager = nullptr;

	static FName INPIN_SpecificActors;
};