// Copyright https://github.com/MothCocoon/FlowGraph/graphs/contributors

#pragma once

#include "AIFlowActorBlackboardHelper.h"
#include "Nodes/AIFlowNode.h"

#include "FlowNode_SetBlackboardValues.generated.h"

// Forward Declarations
class UFlowBlackboardEntryValue;

/**
 * Set blackboard values base class to the values defined in the Entries array
 * "DEPRECATED" in that it will be made Abstract once all of the node instances have been replaced with the subclass
 */
UCLASS(DisplayName = "Set Blackboard Values")
class AIFLOW_API UFlowNode_SetBlackboardValues : public UAIFlowNode
{
	GENERATED_BODY()

public:

	UFlowNode_SetBlackboardValues();

	// IFlowCoreExecutableInterface
	virtual void ExecuteInput(const FName& PinName) override;
	virtual void DeinitializeInstance() override;
	// --

	// UFlowNodeBase
	virtual void UpdateNodeConfigText_Implementation() override;
	// --

#if WITH_EDITOR
public:

	// IFlowContextPinSupplierInterface
	virtual bool SupportsContextPins() const override { return Super::SupportsContextPins() || !EntriesForEveryActor.Entries.IsEmpty(); }
	// --

	// UObject
	virtual void PostEditChangeChainProperty(FPropertyChangedChainEvent& PropertyChangedEvent) override;
	// --

	// IFlowDataPinGeneratorInterface
	virtual void AutoGenerateDataPins(FFlowAutoDataPinsWorkingData& InOutWorkingData) const override;
	// --

	// IFlowBlackboardAssetProvider
	virtual UBlackboardData* GetBlackboardAssetForPropertyHandle(const TSharedPtr<IPropertyHandle>& PropertyHandle) const override;
	// --

protected:

	void AppendEntriesForEveryActor(FTextBuilder& InOutTextBuilder) const;

	UBlackboardData* GetBlackboardAssetForEditor() const;
#endif // WITH_EDITOR

protected:

	TArray<UBlackboardComponent*> GetBlackboardComponentsToApplyTo() const;

	void EnsureInjectComponentsManager();
	void CleanupInjectComponentsManager();

	UFUNCTION()
	void OnBeforeActorRemoved(AActor* RemovedActor);

	// Functions for subclasses to apply additional monitoring to Actors
	virtual void OnStartMonitoringActor(AActor& Actor) { }
	virtual void OnStopMonitoringActor(AActor& Actor) { }

	virtual TArray<AActor*> TryResolveActorsForBlackboard() const;
	virtual bool TryGetPerActorOptions(
		const TArray<FAIFlowConfigureBlackboardOption>*& OutPerActorOptions,
		EPerActorOptionsAssignmentMethod& OutPerActorOptionsAssignmentMethod) const { return false; }

	virtual bool TryFindPropertyByPinName(
		const UObject& PropertyOwnerObject,
		const FName& PinName,
		const FProperty*& OutFoundProperty,
		TInstancedStruct<FFlowDataPinValue>& OutFoundInstancedStruct) const override;

protected:

	// Blackboard properties to set on each actor this node is applied to
	UPROPERTY(EditAnywhere, Category = Configuration, meta = (ShowOnlyInnerProperties, DisplayPriority = 4))
	FAIFlowConfigureBlackboardOption EntriesForEveryActor;

	// Specific blackboard to use (optional, defaults to the flow asset's blackboard)
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Specific Blackboard", meta = (DisplayPriority = 2))
	TObjectPtr<UBlackboardData> SpecificBlackboardAsset = nullptr;

	// Search rule to use to find the "Specific Blackboard" (if specified)
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Blackboard Search Rule", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	EActorBlackboardSearchRule SpecificBlackboardSearchRule = EActorBlackboardSearchRule::ActorAndControllerAndGameState;

	// Injection rule for a missing blackboard on the actor
	UPROPERTY(EditAnywhere, Category = Configuration, DisplayName = "Blackboard Injection Rule", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	EActorBlackboardInjectRule InjectRule = EActorBlackboardInjectRule::DoNotInjectIfMissing;

	// Specific blackboard component subclass to use (optional, defaults to the flow asset's blackboard defined component class)
	UPROPERTY(EditAnywhere, AdvancedDisplay, Category = Configuration, DisplayName = "Specific Blackboard Component", meta = (EditCondition = "SpecificBlackboardAsset", DisplayAfter = SpecificBlackboardAsset))
	TSubclassOf<UBlackboardComponent> SpecificBlackboardComponentClass = nullptr;

	// Helper struct that shared functionality for manipulating Actor blackboards
	UPROPERTY()
	FAIFlowActorBlackboardHelper ActorBlackboardHelper;

	// Manager object to inject and remove components from actors
	UPROPERTY(Transient)
	TObjectPtr<UFlowInjectComponentsManager> InjectComponentsManager = nullptr;
};
